chequeados/api/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^chequeados/$',
		views.ArticuloListView.as_view(),
		name='chequeados_lista'),
	
	url(r'^chequeados/(?P<pk>\d+)/$',
		views.ArticuloListView.as_view(),
		name='chequeados_lista'),

	url(r'^categoria/(?P<pk>[0-9]+)/$',
		views.articulos_list,
		name='categoria_lista'),
]

chequeados/urls.py
from django.conf.urls import url
from django.conf.urls import include

from . import views
urlpatterns = [
	# post views
	url(r'^$', views.articulo_list, name='articulo_list'),
	url(r'^chequeado/(?P<articulo>[-\w]+)/$', views.articulo_detail, name='articulo_detail'),
	url(r'^categoria/(?P<categoria>[-\w]+)/$', views.categoria_list, name='categoria_list'),
	url(r'^api/', include('chequeados.api.urls', namespace='api')),
	# url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
	# 	r'(?P<post>[-\w]+)/$',
	# 	views.post_detail,
	# 	name='post_detail')
]

hack/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chequeados/', include('chequeados.urls',
    	namespace='chequeados',
    	app_name='chequeados')),
]

chequeados/models.py
from django.db import models
from django.conf import settings

# Create your models here.
from django.utils import timezone
from django.contrib.auth.models import User

class Categoria(models.Model):
	title    = models.CharField(max_length=200, db_index=True)
	slug     = models.SlugField(max_length=200, db_index=True, unique=True)
	main_img = models.ImageField(upload_to='categorias/',max_length=255)

	class Meta:
		ordering = ('title',)
		verbose_name = 'categoría'
		verbose_name_plural = 'categorías'
	
	def __str__(self):
		return self.title

class Empresa(models.Model):
	title             = models.CharField(max_length=200, db_index=True)
	slug              = models.SlugField(max_length=200, db_index=True, unique=True)
	small_description = models.TextField()
	avatar            = models.ImageField(upload_to='empresas/',max_length=255)
	avatar_white     = models.ImageField(upload_to='empresas/',max_length=255, null=True)

	class Meta:
		ordering = ('title',)
		verbose_name = 'empresa'
		verbose_name_plural = 'empresas'
	
	def __str__(self):
		return self.title

class Articulo(models.Model):
	STATUS_CHOICES = (
		('draft', 'Draft'),
		('published', 'Published'),
		)

	title      = models.CharField(max_length=250)
	slug       = models.SlugField(max_length=250, unique=True)
	author     = models.ForeignKey(Empresa, related_name='chequeado_empresa')
	category   = models.ForeignKey(Categoria, related_name='chequeado_categoria', default=0)
	main_img   = models.ImageField(upload_to='subidas/%m-%Y/',max_length=255)
	intro_text = models.TextField(null=True)
	body       = models.TextField()
	likes      = models.IntegerField(default=0)
	publish    = models.DateTimeField(default=timezone.now)
	created    = models.DateTimeField(auto_now_add=True)
	updated    = models.DateTimeField(auto_now=True)
	status     = models.CharField(max_length=10,
		choices=STATUS_CHOICES,
		default='draft')

	class Meta:
		ordering = ('-publish',)
		def __str__(self):
			return self.title

	@models.permalink
	def get_absolute_url(self):
		return reverse('chequeados:chequeado',
			args=[self.slug])

chequeados/api/views.py
from rest_framework import generics
from chequeados.models import Articulo
from .serializers import ArticuloSerializer

from rest_framework.decorators import api_view
from rest_framework.response import Response

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render

#from django.core import serializers

@api_view(['GET'])
def articulos_list(request, pk):
    articulos = Articulo.objects.all().filter(category_id=pk)

    if request.method == 'GET':
    	limit = request.GET.get('limit')
    	page = request.GET.get('page')

    	paginator = Paginator(articulos, limit)

    	try:
    		articulos = paginator.page(page)
    	except PageNotAnInteger:
    		articulos = paginator.page(1)
    	except EmptyPage:
    		articulos = ''

    	if paginator.page(page).has_next():
    		next = "http://local.hack.io/chequeados/api/categoria/"+pk+"/?limit="+limit+"&page="+str(paginator.page(page).next_page_number())
    	else:
    		next = None

    	if paginator.page(page).has_previous():
    		previous = "http://local.hack.io/chequeados/api/categoria/"+pk+"/?limit="+limit+"&page="+str(paginator.page(page).previous_page_number())
    	else:
    		previous = None

    	serializer = ArticuloSerializer(articulos, many=True)

    	return Response({
            'count': paginator.count,
    		'next': next,
    		'previous': previous,
            'results': serializer.data
        })

    	
class ArticuloListView(generics.ListAPIView):
	queryset = Articulo.objects.all()
	serializer_class = ArticuloSerializer

class ArticuloDetailView(generics.RetrieveAPIView):
	queryset = Articulo.objects.all()
	serializer_class = ArticuloSerializer

chequeados/views.py
from django.shortcuts import render
from django.core import serializers

# Create your views here.
from django.shortcuts import render, get_object_or_404
from chequeados.models import Articulo
from chequeados.models import Empresa
from chequeados.models import Categoria
def articulo_list(request):
	categorias       = Categoria.objects.all()
	articulos        = Articulo.objects.all()[:4]
	articulos_schema = Articulo.objects.all() #Para MicroData Schema.org
	return render(request,
		'chequeados/articulo/list.html',
		{
			'categorias': categorias,
			'articulos': articulos,
			'articulos_schema': articulos_schema
		})

def categoria_list(request, categoria):
	categoria_actual = Categoria.objects.get(slug__exact=categoria)
	categorias       = Categoria.objects.all()
	articulos        = Articulo.objects.all().filter(category_id=categoria_actual.id)[:4]
	articulos_schema = Articulo.objects.all().filter(category_id=categoria_actual.id) #Para MicroData Schema.org
	return render(request,
		'chequeados/categoria/list.html',
		{
			'categoria_actual': categoria_actual,
			'categorias': categorias,
			'articulos': articulos,
			'articulos_schema': articulos_schema
		})

def articulo_detail(request, articulo):
#Dinámico
	articulo   = get_object_or_404(Articulo, slug=articulo, status='published')
	empresa    = get_object_or_404(Empresa, pk=articulo.author_id)
	categoria  = get_object_or_404(Categoria, pk=articulo.category_id)
	return render(request,
		'chequeados/articulo/article.html',
		{
			'chequeado': articulo,
			'empresa': empresa,
			'categoria': categoria,
		})

chequeados/templates/chequeados/articulo/article.html
{% extends "chequeados/base.html" %}
{% load staticfiles %}
{% block title %}Chequeados{% endblock %}
{% block content %}
<div class="off-canvas-wrapper">
	<div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
		<div class="off-canvas position-left hack-canvas" id="offCanvas" data-off-canvas>
			<div class="row top-canvas">
				<div class="small-9 columns">
					<div class="logo-canvas">
						<img src="{% static "img/logo-menu-mobile.svg" %}" class="logo" alt="Hackealo">
					</div>
				</div>
				<div class="small-3 columns">
					<button class="close-button" aria-label="Close menu" type="button" data-close>
						<span aria-hidden="true"><i class="fa fa-times"></i></span>
					</button>
				</div>
			</div>

			<ul class="vertical menu">
				<li><a href="javascript:void(0);">Sumate a una empresa</a></li>
				<li><a href="javascript:void(0);">Lo que se viene</a></li>          
				<li class="current"><a href="/chequeados">Chequeados</a></li> 
			</ul>
		</div>
		<div class="off-canvas-content" data-off-canvas-content>
			<div id="content" class="chequeado">
				<header id="header">
					<div class="navigation">
						<div class="row expanded">
							<div class="large-5 columns show-for-large">
								<nav id="navigation" class="">                      
									<ul id="header-nav" class="nav navbar-nav menu">              
										<li><a href="javascript:void(0);">Sumate a una empresa</a></li>
										<li><a href="javascript:void(0);">Lo que se viene</a></li>          
										<li class="current"><a href="/chequeados">Chequeados</a></li>     
									</ul>
								</nav>
							</div>
							<div class="large-2 columns logo">
								<button type="button" class="button hide-for-large offmenu" data-toggle="offCanvas"><i class="fa fa-bars"></i></button>
								<img src="{% static "img/logo.svg" %}" class="logo" alt="Hackealo">
							</div>
							<div class="large-5 columns navbar-col show-for-large">
								<ul class="nav navbar-nav navbar-right menu">
									<li><a href="javascript:void(0);" class="user-btn">¡Tu voto vale! <i class="fa fa-gift"></i></a></li>
									<li><a href="javascript:void(0);" class="user-btn"><i class="fa fa-user"></i></a></li>
									<li><span class="filter-btn sb-toggle-right"><i class="fa fa-filter"></i></span></li>
								</ul>
							</div>
						</div>
					</div>
				</header>
				<section id="contenido">
					<div class="row expanded">
						<div class="img_principal" style="background: linear-gradient(rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.0)), url('/media/{{ chequeado.main_img }}') center center;">
							<div class="info_empresa">
								<img src="/media/{{ empresa.avatar_white }}" alt="{{ empresa.title }}">
								<p>{{ empresa.title }}</p>
							</div>
							<h1>{{ chequeado.title }}</h1>
						</div>
					</div>
					<div class="row">
						<div class="large-8 small-centered columns">
							<div class="articulo_solo">
								<p class="read_time">
									<i class="fa fa-bookmark"></i> Lectura de <span class="tiempo_lectura"></span> min
								</p>
								<div class="cuerpo_articulo">
									{{ chequeado.body|safe }}
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="large-8 small-centered columns">
							<div class="row">
								<div class="large-12 small-centered columns">
									<span class="likes"><i class="fa fa-heart-o"></i> {{ chequeado.likes }}</span>
								</div>
								<div class="large-6 small-6 columns">
									{% if chequeado.get_previous_by_created %}
										<a href="{% url 'chequeados:articulo_detail' chequeado.get_previous_by_created.slug %}" class="pag-chequeado prev"><strong><<</strong> Anterior chequeado</a>
									{% endif %}
								</div>
								<div class="large-6 small-6 columns">
									{% if chequeado.get_next_by_created %}
										<a href="{% url 'chequeados:articulo_detail' chequeado.get_next_by_created.slug %}" class="pag-chequeado next">Siguiente chequeado <strong>>></strong></a>
									{% endif %}
								</div>
							</div>
						</div>
					</div>
				</section>
				<footer id="footer">
					<div class="row">
						<div class="large-6 columns">
							<div class="footer-brand">
								<a href="/">  
									<img src="{% static "img/logo-footer.svg" %}" class="img-responsive" alt="Hackealo">             
								</a>
								<p class="lead-copyright">El primer sitio de empleos pensado por y para programadores, donde las empresas compiten por contratarte.</p>
							</div>  
						</div>
						<div class="large-3 columns">
							<ul class="links">
								<li><a href="#">Servicios a empresas</a></li>
								<li><a href="#">Quienes somos</a></li>
								<li><a href="#">Politicas de privacidad</a></li>
								<li><a href="#">Terminos y Condiciones</a></li>
							</ul>
						</div>
						<div class="large-3 columns">
							<p class="copyright"><strong>© 2015 Hackealo.co</strong>  Todos los derechos reservados</p>
						</div>
					</div>
				</footer>
			</div>
		</div>
	</div>
</div>

{% endblock %}

chequeados/templates/chequeados/articulo/list.html
{% extends "chequeados/base.html" %}
{% load staticfiles %}
{% block title %}Chequeados{% endblock %}
{% block content %}
<script type="text/javascript">
	{% if articulos_schema.count > articulos.count %}
	var page = 2; //Pagina de la API cuando se usa una variable específica.
	{% endif %}
</script>
<div class="off-canvas-wrapper">
	<div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
		<div class="off-canvas position-left hack-canvas" id="offCanvas" data-off-canvas>
			<div class="row top-canvas">
				<div class="small-9 columns">
					<div class="logo-canvas">
						<img src="{% static "img/logo-menu-mobile.svg" %}" class="logo" alt="Hackealo">
					</div>
				</div>
				<div class="small-3 columns">
					<button class="close-button" aria-label="Close menu" type="button" data-close>
						<span aria-hidden="true"><i class="fa fa-times"></i></span>
					</button>
				</div>
			</div>

			<ul class="vertical menu">
				<li><a href="javascript:void(0);">Sumate a una empresa</a></li>
				<li><a href="javascript:void(0);">Lo que se viene</a></li>          
				<li class="current"><a href="/chequeados">Chequeados</a></li> 
			</ul>
		</div>
		<div class="off-canvas-content" data-off-canvas-content>
			<div id="content">
				<header id="header">
					<div class="navigation">
						<div class="row expanded">
							<div class="large-5 columns show-for-large">
								<nav id="navigation" class="">                      
									<ul id="header-nav" class="nav navbar-nav menu">              
										<li><a href="javascript:void(0);">Sumate a una empresa</a></li>
										<li><a href="javascript:void(0);">Lo que se viene</a></li>          
										<li class="current"><a href="/chequeados">Chequeados</a></li>     
									</ul>
								</nav>
							</div>
							<div class="large-2 columns logo">
								<button type="button" class="button hide-for-large offmenu" data-toggle="offCanvas"><i class="fa fa-bars"></i></button>
								<img src="{% static "img/logo.svg" %}" class="logo" alt="Hackealo">
							</div>
							<div class="large-5 columns navbar-col show-for-large">
								<ul class="nav navbar-nav navbar-right menu">
									<li><a href="javascript:void(0);" class="user-btn">¡Tu voto vale! <i class="fa fa-gift"></i></a></li>
									<li><a href="javascript:void(0);" class="user-btn"><i class="fa fa-user"></i></a></li>
									<li><span class="filter-btn sb-toggle-right"><i class="fa fa-filter"></i></span></li>
								</ul>
							</div>
						</div>
					</div>
				</header>
				<section id="content">
					<div class="row expanded">
						<div class="large-4 columns banner">
							<div class="main-banner">
								<h3>Chequeados</h3>
								<p>Te contamos lo que te interesa saber de las empresas que te están buscando.</p>
							</div>
						</div>
						{% verbatim %}
						<script id="articulo-template" type="text/x-handlebars-template">
							{{#each this}}
							<div class="row">
								<div class="articulo">
									<div class="large-10 columns end">
										<div class="row">
											<div class="small-10 columns">
												<a href="/chequeados/chequeado/{{ slug }}" title="{{title}}"><h2 class="title">{{ title }}</h2></a>
												<div class="description">{{{ intro_text }}}</div>
											</div>
											<div class="small-2 end columns">
												<!-- os.split() -->
												<img src="{{author.avatar}}" alt="{{author.title}}">
											</div>
										</div>
										<div class="row">
											<div class="large-4 small-5 columns">
												<p class="category">{{category.title}}</p>
											</div>
											<div class="large-3 small-3 columns end">
												<span class="likes"><i class="fa fa-heart-o"></i> {{likes}}</span>
											</div>
										</div>
									</div>
								</div>
							</div>
							{{/each}}
						</script>
						{% endverbatim %}
						<div class="large-8 columns posts-list">
							<div class="posts">
								<ul class="menu nav-posts">
									<li class="current" id="btn_all"><a href="javascript:void(0);" title="Todos los chequeados">Todos los chequeados</a></li>
									<li id="btn_categories"><a href="javascript:void(0);" title="Todos los chequeados">Categorías</a></li>
								</ul>
								<div class="posts-handle">
									{% for chequeado in articulos %}
									<div class="row">
										<div class="articulo">
											<div class="large-10 columns end">
												<div class="row">
													<div class="small-10 columns">
													<a href="/chequeados/chequeado/{{ chequeado.slug }}" title="{{ chequeado.title }}"><h2 class="title">{{ chequeado.title }}</h2></a>
														<div class="description">{{ chequeado.intro_text |safe }}</div>
													</div>
													<div class="small-2 end columns">
														<!-- os.split() -->
														<img src="/media/{{chequeado.author.avatar}}" alt="{{chequeado.author.title}}">
													</div>
												</div>
												<div class="row">
													<div class="large-4 small-5 columns">
														<p class="category">{{chequeado.category.title}}</p>
													</div>
													<div class="large-3 small-3 columns end">
														<span class="likes"><i class="fa fa-heart-o"></i> {{chequeado.likes}}</span>
													</div>
												</div>
											</div>
										</div>
									</div>
									{% endfor %}
									<div class="load">
										<span class="animation"></span>
										<span class="texto">Cargando, espera un poco</span>
									</div>
								</div>
								<div class="categories-handle">
									<div class="row">
										<div class="large-10 columns end">
											<div class="row small-up-2 medium-up-3 c-list">
												{% for categoria in categorias %}
												<div class="categoria column">
													<div class="categoria-info">
														<a href="/chequeados/categoria/{{ categoria.slug }}" title="{{ categoria.title }}">
															<img src="/media/{{ categoria.main_img }}" alt="{{ categoria.title }}">
															<h3>{{ categoria.title }}</h3>
														</a>
													</div>
												</div>
												{% endfor %}
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	</div>
</div>
{% endblock %}

chequeados/templates/chequeados/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js" lang="en" dir="ltr">
<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{% endblock %}</title>
	<link rel="canonical" href="{{request.build_absolute_uri}}">
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900|Droid+Serif" rel="stylesheet"> 
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet"> 
	<link href="{% static "css/foundation.min.css" %}" rel="stylesheet">
	<link href="{% static "css/app.css" %}" rel="stylesheet">
</head>
<body>
	{% block content %}
	{% endblock %}
	<script src="{% static "js/vendor/jquery.js" %}" defer></script>
	<script src="{% static "js/vendor/what-input.js" %}" defer></script>
	<script src="{% static "js/vendor/foundation.min.js" %}" defer></script>
	<script src="{% static "js/vendor/handlebars.js" %}" defer></script>
	<script src="{% static "js/vendor/enquire.min.js" %}" defer></script>
	<script src="{% static "js/app.js" %}" defer></script>
</body>
</html>

chequeados/templates/chequeados/categoria/list.html
{% extends "chequeados/base.html" %}
{% load staticfiles %}
{% block title %}Chequeados. Categoría: {{ categoria_actual.title }} {% endblock %}
{% block content %}
<script type="text/javascript">
	var cat_principal = {{ categoria_actual.id }};
	{% if articulos_schema.count > articulos.count %}
	var page = 2; //Pagina de la API cuando se usa una variable específica.
	{% endif %}
</script>
<div class="off-canvas-wrapper">
	<div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
		<div class="off-canvas position-left hack-canvas" id="offCanvas" data-off-canvas>
			<div class="row top-canvas">
				<div class="small-9 columns">
					<div class="logo-canvas">
						<img src="{% static "img/logo-menu-mobile.svg" %}" class="logo" alt="Hackealo">
					</div>
				</div>
				<div class="small-3 columns">
					<button class="close-button" aria-label="Close menu" type="button" data-close>
						<span aria-hidden="true"><i class="fa fa-times"></i></span>
					</button>
				</div>
			</div>

			<ul class="vertical menu">
				<li><a href="javascript:void(0);">Sumate a una empresa</a></li>
				<li><a href="javascript:void(0);">Lo que se viene</a></li>          
				<li class="current"><a href="/chequeados">Chequeados</a></li> 
			</ul>
		</div>
		<div class="off-canvas-content" data-off-canvas-content>
			<div id="content">
				<header id="header">
					<div class="navigation">
						<div class="row expanded">
							<div class="large-5 columns show-for-large">
								<nav id="navigation" class="">                      
									<ul id="header-nav" class="nav navbar-nav menu">              
										<li><a href="javascript:void(0);">Sumate a una empresa</a></li>
										<li><a href="javascript:void(0);">Lo que se viene</a></li>          
										<li class="current"><a href="/chequeados">Chequeados</a></li>     
									</ul>
								</nav>
							</div>
							<div class="large-2 columns logo">
								<button type="button" class="button hide-for-large offmenu" data-toggle="offCanvas"><i class="fa fa-bars"></i></button>
								<img src="{% static "img/logo.svg" %}" class="logo" alt="Hackealo">
							</div>
							<div class="large-5 columns navbar-col show-for-large">
								<ul class="nav navbar-nav navbar-right menu">
									<li><a href="javascript:void(0);" class="user-btn">¡Tu voto vale! <i class="fa fa-gift"></i></a></li>
									<li><a href="javascript:void(0);" class="user-btn"><i class="fa fa-user"></i></a></li>
									<li><span class="filter-btn sb-toggle-right"><i class="fa fa-filter"></i></span></li>
								</ul>
							</div>
						</div>
					</div>
				</header>
				<section id="content">
					<div class="row expanded">
						<div class="large-4 columns banner">
							<div class="main-banner" style="background: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), url(/media/{{ categoria_actual.main_img }}) top left no-repeat;">
								<h3>{{categoria_actual.title}}</h3>
								<p>Te contamos lo que te interesa saber de las empresas que te están buscando.</p>
							</div>
						</div>
						{% verbatim %}
						<script id="articulo-template" type="text/x-handlebars-template">
							{{#each this}}
							<div class="row">
								<div class="articulo">
									<div class="large-10 columns end">
										<div class="row">
											<div class="small-10 columns">
												<a href="/chequeados/chequeado/{{ slug }}" title="{{title}}"><h2 class="title">{{ title }}</h2></a>
												<div class="description">{{{ intro_text }}}</div>
											</div>
											<div class="small-2 end columns">
												<!-- os.split() -->
												<img src="{{author.avatar}}" alt="{{author.title}}">
											</div>
										</div>
										<div class="row">
											<div class="large-4 small-5 columns">
												<p class="category">{{category.title}}</p>
											</div>
											<div class="large-3 small-3 columns end">
												<span class="likes"><i class="fa fa-heart-o"></i> {{likes}}</span>
											</div>
										</div>
									</div>
								</div>
							</div>
							{{/each}}
						</script>
						{% endverbatim %}
						<div class="large-8 columns posts-list">
							<div class="posts">
								<ul class="menu nav-posts">
									<li class="current" id="btn_all"><a href="javascript:void(0);" title="Todos los chequeados">Todos los chequeados</a></li>
									<li id="btn_categories"><a href="javascript:void(0);" title="Todos los chequeados">Categorías</a></li>
								</ul>
								<div class="posts-handle">
									{% for chequeado in articulos %}
									<div class="row">
										<div class="articulo">
											<div class="large-10 columns end">
												<div class="row">
													<div class="small-10 columns">
													<a href="/chequeados/chequeado/{{ chequeado.slug }}" title="{{ chequeado.title }}"><h2 class="title">{{ chequeado.title }}</h2></a>
														<div class="description">{{ chequeado.intro_text |safe }}</div>
													</div>
													<div class="small-2 end columns">
														<!-- os.split() -->
														<img src="/media/{{chequeado.author.avatar}}" alt="{{chequeado.author.title}}">
													</div>
												</div>
												<div class="row">
													<div class="large-4 small-5 columns">
														<p class="category">{{chequeado.category.title}}</p>
													</div>
													<div class="large-3 small-3 columns end">
														<span class="likes"><i class="fa fa-heart-o"></i> {{chequeado.likes}}</span>
													</div>
												</div>
											</div>
										</div>
									</div>
									{% endfor %}
								</div>
								<div class="load">
									<span class="animation"></span>
									<span class="texto">Cargando, espera un poco</span>
								</div>

								<div class="categories-handle">
									<div class="row">
										<div class="large-10 columns end">
											<div class="row small-up-2 medium-up-3 c-list">
												{% for categoria in categorias %}
												<div class="categoria column">
													<div class="categoria-info">
														<a href="/chequeados/categoria/{{ categoria.slug }}" title="{{ categoria.title }}">
															<img src="/media/{{ categoria.main_img }}" alt="{{ categoria.title }}">
															<h3>{{ categoria.title }}</h3>
														</a>
													</div>
												</div>
												{% endfor %}
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	</div>
</div>
{% endblock %}